### PR TITLE
Fix Windows CLI problems

### LINKED ISSUE #428: Multiple write error when initializing a bucket
PS C:\Users\Milena\Desktop\dev\github\intootv-backend\bucket> hub bucket init
Enter a name for your new bucket (optional): intooTV█
Enter a name for your new bucket (optional): intooTV█
x Encrypt bucket contents:
x Encrypt bucket contents:
> Selected threadDB Create new
Enter a name for your new threadDB (optional): intooTV█
Enter a name for your new threadDB (optional): intooTV█
←[31m> Error! ←[90mMultiple write errors: [{write errors: [{E11000 duplicate key error collection: textile.threads index: _id.owner_1_name_1 collation: { locale: "en", caseLevel: false, caseFirst: "off", strength: 2, numericOrdering: false, alternate: "non-ignorable", maxVariable: "punct", normalization: false, backwards: false, version: "57.1" } dup key: { _id.owner: BinData(0, 0801122089738ECC72D60D5943EE98D023695EC3CB8A788734A5AC725DDB078EF1A5758A), name: "0x39434f45454f53010b" }}]}, {<nil>}]←[0m←[0m

### PR DESCRIPTION
**Pull request by jsign**
This fixes multiples Hub CLI problems in Windows. 
There were three main problems:
- We had an assumption of `/` being the path separator, which is now changed to `runtime.OsPathSeparator` to be platform-independent.
- The `uiprogress` component used in pushing files doesn't work in Windows, it tries to use `stty` with error: `←[31m> Error! ←[90mExec: "stty": executable file not found in %!P(MISSING)ATH%!←(MISSING)[0m←[0m`. I changed to detect if that's the case and avoid using the component but explain the event with plain text. (see screenshot below).
- The Windows terminal doesn't support ANSI colors as explained in the `aurora` package we use for coloring terminal output. I changed the `aurora` reference to a custom instance which enables or disables coloring depending on the OS.

Before it printed ANSI Colors characters which were very confusing for UX, like:
`←[31m> Error! ←[90mSome errors or similar←[0m←[0m`

Example of how it looks now:
image
So there you can see:
- No ANSI color characters in outputs.
- Progress bars changed to plaintext explanation of the event.
- `.textile` folder is ignored as expected, and #428 is fixed.

Fixes #428

### CODE REVIEW

File: cmd/buck/cli/util.go [hunk 1]
```diff
@@ -37,8 +38,15 @@ func handleProgressBars(p *uiprogress.Progress, events chan local.PathEvent) {
...
 		case local.FileStart:
+			if runtime.GOOS == "windows" {
+				cmd.Message("Uploading %s", e.Path)
+				continue
+			}
 			bars[e.Path] = addBar(p, e.Path, e.Size)
 		case local.FileProgress, local.FileComplete:
+			if runtime.GOOS == "windows" {
+				continue
+			}
```
Comment (jsign) [inline cmd/buck/cli/util.go:49]: We could be creative here and print some dots on progress, but that might create a weird output if the file is too big and the screen gets full of dots. Another option is crafting a way of always printing the % of progress but I'd guess that requires some careful deletion of already printed values and re-printing; sounds like something a library should do.

Sounds to me that we should explore eventually an `uiprogress` similar component that works well in all OSs, instead of jumping in building our own custom Windows solution.

File: buckets/local/diff.go [hunk 2]
```diff
@@ -4,14 +4,17 @@ import (
...
 	"strings"
 
 	"github.com/ipfs/go-merkledag/dagutils"
-	"github.com/logrusorgru/aurora"
+	aurora2 "github.com/logrusorgru/aurora"
 	"github.com/textileio/textile/v2/buckets"
 	"github.com/textileio/textile/v2/cmd"
 )
 
+var aurora = aurora2.NewAurora(runtime.GOOS != "windows")
```
Comment (jsign) [inline buckets/local/diff.go:16]: The main trick is basically overriding the `aurora` definition with a custom instance with coloring disabled if appropriate, instead of all places using the static methods of the package directly.

File: cmd/buck/cli/util.go (hunk 1 above)
Comment (textileben) [reply cmd/buck/cli/util.go:49]: I haven't used it, but this golang based UI toolkit looks pretty nice https://github.com/charmbracelet/bubbletea

Comment (jsign) [reply cmd/buck/cli/util.go:49]: Nice, sounds like a good candidate :)

Comment (sanderpick) [reply cmd/buck/cli/util.go:49]: Cool, that looks nice! We've made a [number of custom tweaks](https://github.com/textileio/uiprogress/commits/master) to the `uiprogress` package. Maybe bubbletea supports the things that we're needed. I think the main one is the ability to replace each bar with a final state, e.g., the pushed / pulled Cid. Will take a look!

**Review by sanderpick — APPROVED** [review]
LGTM!
