### PR TITLE
Buckets: Transform roots to Cid V1

### LINKED ISSUE #133: Error when updating an existing bucket
Sometimes fails with `Error! 'From' cid was not recursively pinned already`

Once a bucket fails with this error, it doesn't seem possible to recover. 

https://github.com/textileio/gatsby-ipfs-blog/runs/515379641#step:6:20 

short term solution is to start a new bucket

### LINKED ISSUE #196: Impossible to register with a slow email setup
It can easily take several minutes for me to receive an email. This makes it impossible to confirm my email to register an account.

Ideally, the initialization process would:

1. Be resumable.
2. Re-poll the textile hub when it times out.

### LINKED ISSUE #201: Use Cid v1 as bucket roots

### PR DESCRIPTION
**Pull request by sanderpick**
Closes #201 
Closes #196 
Closes #133

### CODE REVIEW

File: api/buckets/service.go [hunk 1]
```diff
@@ -82,16 +82,20 @@ func (s *Service) createBucket(ctx context.Context, dbID thread.ID, dbToken thre
 		ipfsfiles.NewMapDirectory(map[string]ipfsfiles.Node{
 			seedName: ipfsfiles.NewBytesFile(seed),
 		}),
-		options.Unixfs.Pin(true))
+		options.Unixfs.Pin(false))
```
Comment (jsign) [inline api/buckets/service.go:85]: Any words on this change?
Seems like as is no Cids are pinned. I'm not sure how the Pin update behaves if its moving a pin which wasn't `.Pin(true)`. Also, if the IPFS node runs GC before a further PushPath is done, we'll lose the bucket.

File: api/buckets/service.go [hunk 2]
```diff
@@ -398,13 +402,18 @@ func (s *Service) PushPath(server pb.API_PushPathServer) error {
...
+	dirpth, err := s.IPFSClient.Object().AddLink(server.Context(), buckPath, filePath, pth, options.Object.Create(true))
 	if err != nil {
 		return err
 	}
 	if err = s.IPFSClient.Pin().Update(server.Context(), buckPath, dirpth); err != nil {
-		return err
+		if err.Error() == "'from' cid was not recursively pinned already" {
+			if err = s.IPFSClient.Pin().Add(server.Context(), dirpth); err != nil {
+				return err
+			}
```
Comment (jsign) [inline api/buckets/service.go:413]: Uhm, I see. This answers my last question. A bit worried about Error string changes and breaking this logic.
Maybe your wording about why the bucket now isn't pinned from start will light this.

Comment (sanderpick) [reply api/buckets/service.go:413]: Yeah, there are not sentinels from the HTTP client :( Maybe an issue over there would be a good idea.

File: api/buckets/service.go (hunk 1 above)
Comment (sanderpick) [reply api/buckets/service.go:85]: The problem with pinning here is that the Cid V0 is pinned, and then below when we update it, it will error w/ "'from' cid was not recursively pinned already", since we'll be asking about the Cid V1. Instead, we add it, then on the next line, manually (recursively) pin the Cid in V1 form.

File: api/buckets/service.go (hunk 2 above)
Comment (sanderpick) [reply api/buckets/service.go:413]: Catching this error here just in case something weird happened with the bucket (as reported by some users... though that was an old report). Confusingly, this is not related to the logic in `createBucket`... but pinning the wrong version of the cid would also pop this error.

Comment (sanderpick) [reply api/buckets/service.go:413]: Issue: https://github.com/ipfs/go-ipfs-http-client/issues/100

File: api/buckets/service.go (hunk 1 above)
Comment (jsign) [reply api/buckets/service.go:85]: Ah, I see. Right, the ipfs-node is talking about V0, and you want to pin V1.
Uhm, how unfortunate. It would be good that the ipfs-node can see that both Cids are referring to the same sha256 data. I missed the `.Pin().Add()` below, so looks good.

File: api/buckets/service.go (hunk 2 above)
Comment (jsign) [reply api/buckets/service.go:413]: Yep, sounds good.

File: api/buckets/service.go (hunk 1 above)
Comment (sanderpick) [reply api/buckets/service.go:85]: Oh, actually looks like there a cid version option with add... I'll try that.

Comment (jsign) [reply api/buckets/service.go:85]: Sounds nice!

Comment (sanderpick) [reply api/buckets/service.go]: Well damn, looks like I can ditch that util method all together after specifying the cid version with add.

Comment (jsign) [reply api/buckets/service.go]: Nice! :)
